     - name: install apache on Redhat server
       yum:
         name: "{{package_name}}"
         update_cache: yes
         state: latest

     - name: enable apache services
       service:
         enabled: true
         name: "{{service_name}}"
         state: started

     - name: copy index.html from src to dest
       copy:
         src: "{{index_file}}"
         dest: "{{destination_path}}/{{index_file}}"
       notify: restart Apache
