# Configure 100 users in remote machines using loop
# use group module and user module

- hosts: ubuntuserver
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: Add group for ubuntu ubuntu users 
    group:
      name: Ubuntu-User-Group
      state: present
  
  - name: Add users to Ubuntu group
    user: 
      group: Ubuntu-User-Group
      state: absent
      remove: yes
      name: "{{item}}"
    loop:
      - user1
      - user2
      - user3
      - user4
      - user5
      - user6
      - user7

