- hosts: all
  become_user: root
  become_method: sudo
  become: yes

  tasks:
  - name: install multiple softwares in ubuntu
    apt: 
      name: "{{item}}"
      state: present
    loop:
      - wget
      - ntp
      - zip
      - unzip
    when: ansible_distribution=="Ubuntu"

  - name: install multiple softwares in redhat
    yum:
      name: "{{item}}"
      state: present
    when: ansible_distribution=="RedHat"
    loop:
      - wget
      - chrony
      - zip
      - unzip
