-  hosts: ubuntuservers
   remote_user: ubuntu
   become_user: root
   become_method: sudo
   become: yes

   tasks:
     - name: install apache on ubuntu server 
       apt:
         name: apache2
         update_cache: yes
         state: latest

     - name: enable apache services
       service:
         enabled: true
         name: apache2
         state: started

     - name: copy from src to dest
       copy:
         src: /etc/ansible/srcd/index.html
         dest: /var/www/html/index.html
