- hosts: all
  become_user: root
  become_method: sudo
  become: yes

  vars: 
    package_name: apache2 

  tasks:  
    - name: generate template and send to remote server 
      template:
        src: template-j2.j2
        dest: /opt/result.txt
