-  hosts: ubuntuservers
   remote_user: ubuntu
   become_user: root
   become_method: sudo
   become: yes

   vars:
     service-name: apache2
     package-name: apache2
     destination-path: /var/www/html
     index-file: index.html


   tasks:
     - name: install apache on ubuntu server 
       apt:
         name: "{{package-name}}"
         update_cache: yes
         state: latest

     - name: enable apache services
       service:
         enabled: true
         name: "{{service-name}}"
         state: started

     - name: copy from src to dest
       copy:
         src: "/etc/ansible/srcd/{{index-file}}"
         dest: "{{destination-path}}/{{index-file}}"
